baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Vincent Cavez'
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]

[params]
  themeColor = "theme-base-0a"